### ISSUE TITLE
practice flashcards - remove brackets from display fields

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#22]
practice flashcards - remove brackets from display fields
impact: low but annoying
location: select deck -> Practice Flashcards
all fields in the displayed flashcards are surrounded by []
check the datatype of the supplied fields, are they collection types?

**Comment by nicoten** [comment]
The problem was in the controller, I'll explain:

Before:
params.max = max ?: 1
def flashcardInstance = Flashcard.findAllByDeck(deckInstance, params)

When you use findAll, it returns a list, even if you limit it to one item using the max param. Consequently, when you called print, it was calling the print method on each item in the list and surrounding it with [ ].

To fix it, I changed findAll to just findBy, which returns the first element in the query like this:
Flashcard flashcardInstance = Flashcard.findByDeck(deckInstance, params)
